stages:
  - build

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

build_docker:
  image: docker:latest
  cache: []
  stage: build
  services:
    - docker
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - |
      if [[ "${CI_COMMIT_BRANCH}" == "master" ]]; then
        TAG="prod-${CI_COMMIT_SHORT_SHA}"
        BUILD_ARGS="--build-arg REACT_APP_BACKEND_URL=klaim_website --build-arg NEXT_PUBLIC_STRAPI_TOKEN=b22d2c0e5f3c64cec025aaa7417714e8d33cb12d7448322404221f289fb30c1e64cf2401719a70fa31c4237a19f20b9c5ee85031642b267152c4041033e3c917a5ffa68375c902e9640780e16e2b8d3ac281e54a1ec3c52369f978bbf5d53ff6929e51422c3ffb31b81406bc86979af3556412be0cdffe48f51f9efc9fa62bc3 --build-arg NEXT_PUBLIC_STRAPI_ENDPOINT=https://strapi.dev.klaim.ai/api --build-arg NEXT_PUBLIC_STRAPI_STATIC_ENDPOINT=https://strapi.dev.klaim.ai"
      elif [[ "${CI_COMMIT_BRANCH}" == "develop" ]]; then
        TAG="dev-${CI_COMMIT_SHORT_SHA}"
        BUILD_ARGS="--build-arg REACT_APP_BACKEND_URL=klaim_website --build-arg NEXT_PUBLIC_STRAPI_TOKEN=b22d2c0e5f3c64cec025aaa7417714e8d33cb12d7448322404221f289fb30c1e64cf2401719a70fa31c4237a19f20b9c5ee85031642b267152c4041033e3c917a5ffa68375c902e9640780e16e2b8d3ac281e54a1ec3c52369f978bbf5d53ff6929e51422c3ffb31b81406bc86979af3556412be0cdffe48f51f9efc9fa62bc3 --build-arg NEXT_PUBLIC_STRAPI_ENDPOINT=https://strapi.dev.klaim.ai/api --build-arg NEXT_PUBLIC_STRAPI_STATIC_ENDPOINT=https://strapi.dev.klaim.ai"
      else
        echo "Branch ${CI_COMMIT_BRANCH} is not master or develop. Skipping build and push."
        exit 0
      fi
    - docker build $BUILD_ARGS -t ${CI_REGISTRY_PATH}/${CI_PROJECT_PATH}:${TAG} .
    - docker push ${CI_REGISTRY_PATH}/${CI_PROJECT_PATH}:${TAG}
  rules:
    - if: '$CI_COMMIT_BRANCH'
