version: "3.7"

services:
  nextjs:
    container_name: ${APP_NAME}_nextjs
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    build:
      context: .
    depends_on:
      - strapi
    networks:
      - klaim_network
  strapi:
    container_name: ${APP_NAME}_strapi
    command: npm run develop
    volumes:
      - ./strapi:/app
      - /app/node_modules
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: klaim_website
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: klaim
      DATABASE_PASSWORD: klaim
    ports:
      - 1337:1337
    build:
      context: ./strapi
    depends_on:
      - mysql
    networks:
      - klaim_network
  mysql:
    image: mariadb:10.6
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: klaim_website
      MYSQL_USER: klaim
      MYSQL_PASSWORD: klaim
      MYSQL_ROOT_PASSWORD: klaim
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - klaim_network
networks:
  klaim_network:
    name: ${APP_NAME}_network
    driver: bridge
