apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: dev-klaim-website
  labels:
    app: dev-klaim-website
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dev-klaim-website
  template:
    metadata:
      labels:
        app: dev-klaim-website
    spec:
      containers:
        - name: dev-klaim-website
          image: klaimregistry.azurecr.io/klaimregistry/dev-klaim-website
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  namespace: dev
  name: dev-klaim-website-svc
spec:
  selector:
    app: dev-klaim-website
  ports:
    - port: 80
      targetPort: 3000
