apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: dev-klaim-website-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "36000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "36000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "36000"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: dev.klaim.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-klaim-website-svc
                port:
                  number: 80

  tls:
    - hosts:
        - dev.klaim.ai
      secretName: dev-klaim-website-tls
