app:
  listenPort: 3000

service:
  enabled: true

ingress:
  enabled: true
  className: nginx-public
  tlsEnabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

deployment:
  annotations:
    reloader.stakater.com/auto: "true"
